services:
  opendevin:
    image: opendevin:0.1.4
    container_name: opendevin
    privileged: true
    runtime: nvidia
    tty: true
    ulimits:
      memlock: -1
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
    ports:
      - "80:80"
      - "3000:3000"
      - "3001:3001"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
    networks:
      - opendevin

networks:
  opendevin:
    external: true
    name: opendevin
